# Generated by Django 2.1.5 on 2019-02-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Məktəb', 'verbose_name_plural': 'Mətkəblər'},
        ),
    ]
