# Generated by Django 2.1.5 on 2019-02-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools_app', '0002_auto_20190210_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='Schools',
        ),
    ]
