# Generated by Django 2.1.5 on 2019-02-10 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('legislation_file', models.FileField(upload_to='media', verbose_name='Yükləmə')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies')),
            ],
            options={
                'verbose_name': 'Qanunvericilik',
                'verbose_name_plural': 'Qanunvericilik',
            },
        ),
    ]
