# Generated by Django 2.1.5 on 2019-01-23 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_app', '0018_remove_companies_legislation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('legislation_file', models.FileField(upload_to='media')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies')),
            ],
        ),
    ]
