# Generated by Django 2.1.5 on 2019-02-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislation',
            options={'verbose_name': 'Qanunvericilik', 'verbose_name_plural': 'Qanunvericilik'},
        ),
        migrations.AlterField(
            model_name='legislation',
            name='legislation_file',
            field=models.FileField(upload_to='media', verbose_name='Yükləmə'),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Başlıq'),
        ),
    ]
