# Generated by Django 2.1.5 on 2019-01-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(choices=[('EM', 'Email'), ('PH', 'Phone'), ('FB', 'Facebook'), ('ADD', 'Address')], default='EM', max_length=25)),
                ('contact', models.CharField(max_length=255)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies')),
            ],
            options={
                'verbose_name': 'Company Contact',
                'verbose_name_plural': 'Company Contacts',
            },
        ),
        migrations.CreateModel(
            name='ContactCompanyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject_placeholder', models.CharField(max_length=255)),
                ('content_placeholder', models.CharField(max_length=1000)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies')),
            ],
        ),
        migrations.CreateModel(
            name='ContactCompanyReceivedEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=1000)),
                ('from_email', models.EmailField(max_length=254)),
                ('sent', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('company_contact_form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_app.ContactCompanyForm')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMainForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject_placeholder', models.CharField(max_length=255)),
                ('content_placeholder', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMainReceivedEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=1000)),
                ('from_email', models.EmailField(max_length=254)),
                ('sent', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
