# Generated by Django 2.1.5 on 2019-02-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactcompany',
            options={'verbose_name': 'Şirkətin əlaqə məlumatı', 'verbose_name_plural': 'Əlaqə məlumatları'},
        ),
        migrations.RenameField(
            model_name='contactcompany',
            old_name='company_id',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='contactcompany',
            name='company_type',
            field=models.IntegerField(choices=[(1, 'Email'), (2, 'Telefon'), (3, 'Facebook'), (4, 'Adres')], default=1, max_length=25),
        ),
    ]
