# Generated by Django 2.1.5 on 2019-02-10 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcompany',
            name='company_contact_form',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contact_app.ContactCompanyForm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactcompanyreceivedemails',
            name='company_contact_form',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contact_app.ContactCompanyForm'),
            preserve_default=False,
        ),
    ]
