# Generated by Django 2.1.5 on 2019-02-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0002_auto_20190205_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcompany',
            name='company_type',
            field=models.IntegerField(choices=[(1, 'Email'), (2, 'Telefon'), (3, 'Facebook'), (4, 'Adres')], default=1),
        ),
    ]
