# Generated by Django 2.1.5 on 2019-02-10 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_auto_20190210_0932'),
        ('contact_app', '0002_auto_20190210_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactcompany',
            name='company_contact_form',
        ),
        migrations.AddField(
            model_name='contactcompany',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies'),
            preserve_default=False,
        ),
    ]
