# Generated by Django 2.1.5 on 2019-02-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0003_auto_20190205_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactcompany',
            old_name='company_type',
            new_name='contact_type',
        ),
        migrations.RenameField(
            model_name='contactcompanyform',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='contactcompanyreceivedemails',
            old_name='company_contact_form_id',
            new_name='company_contact_form',
        ),
        migrations.AlterField(
            model_name='contactcompanyreceivedemails',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
