# Generated by Django 2.1.5 on 2019-02-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0004_auto_20190205_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcompany',
            name='contact_type',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 2), (4, 4), (5, 5)], default=1),
        ),
    ]
