# Generated by Django 2.1.5 on 2019-02-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0005_auto_20190207_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcompany',
            name='contact_type',
            field=models.IntegerField(choices=[('Email', 1), ('Telefon', 2), ('Adres', 4), ('Faks', 5)], default=1),
        ),
    ]
