# Generated by Django 2.1.5 on 2019-02-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0006_auto_20190207_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactcompanyreceivedemails',
            options={'verbose_name': 'Gələn məktub', 'verbose_name_plural': 'Gələn məktublar'},
        ),
        migrations.AlterField(
            model_name='contactcompany',
            name='contact_type',
            field=models.IntegerField(choices=[(1, 'Email'), (2, 'Telefon'), (4, 'Adres'), (5, 'Faks')], default=1),
        ),
    ]
