# Generated by Django 2.1.5 on 2019-02-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0007_auto_20190207_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactcompanyform',
            options={'verbose_name': 'Əlaqə formasının ayarları', 'verbose_name_plural': 'Əlaqə formasının ayarları'},
        ),
        migrations.AlterField(
            model_name='contactcompanyform',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies'),
        ),
        migrations.AlterField(
            model_name='contactcompanyform',
            name='content_placeholder',
            field=models.CharField(max_length=1000, verbose_name='Mətn üçün qeyd'),
        ),
        migrations.AlterField(
            model_name='contactcompanyform',
            name='subject_placeholder',
            field=models.CharField(max_length=255, verbose_name='Mövzu üçün qeyd'),
        ),
        migrations.AlterField(
            model_name='contactcompanyform',
            name='to_email',
            field=models.EmailField(max_length=254, verbose_name='Kimə'),
        ),
    ]
