# Generated by Django 2.1.5 on 2019-02-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0008_auto_20190207_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcompanyform',
            name='content_placeholder',
            field=models.CharField(default='Məktubun mətni', max_length=1000, verbose_name='Mətn üçün qeyd'),
        ),
        migrations.AlterField(
            model_name='contactcompanyform',
            name='subject_placeholder',
            field=models.CharField(default='Məktubun mövzusu', max_length=255, verbose_name='Mövzu üçün qeyd'),
        ),
    ]
