# Generated by Django 2.1.5 on 2019-02-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0009_auto_20190207_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactcompanyform',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contactcompanyreceivedemails',
            name='company_contact_form',
        ),
        migrations.DeleteModel(
            name='ContactCompanyForm',
        ),
        migrations.DeleteModel(
            name='ContactCompanyReceivedEmails',
        ),
    ]
