# Generated by Django 2.1.5 on 2019-02-07 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0051_auto_20190205_0430'),
        ('contact_app', '0010_auto_20190207_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCompanyForm',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='company_app.Companies')),
                ('to_email', models.EmailField(max_length=254, verbose_name='Kimə')),
                ('subject_placeholder', models.CharField(default='Məktubun mövzusu', max_length=255, verbose_name='Mövzu üçün qeyd')),
                ('content_placeholder', models.CharField(default='Məktubun mətni', max_length=1000, verbose_name='Mətn üçün qeyd')),
            ],
            options={
                'verbose_name': 'Əlaqə formasının ayarları',
                'verbose_name_plural': 'Əlaqə formasının ayarları',
            },
        ),
        migrations.CreateModel(
            name='ContactCompanyReceivedEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=1000)),
                ('from_email', models.EmailField(max_length=254)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('company_contact_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_app.ContactCompanyForm')),
            ],
            options={
                'verbose_name': 'Gələn məktub',
                'verbose_name_plural': 'Gələn məktublar',
            },
        ),
    ]
