# Generated by Django 2.1.5 on 2019-02-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0011_contactcompanyform_contactcompanyreceivedemails'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcompanyform',
            name='email_placeholder',
            field=models.CharField(default='Email adresinizi daxil edin', max_length=255, verbose_name='Email üçün qeyd'),
        ),
        migrations.AddField(
            model_name='contactcompanyform',
            name='name_placeholder',
            field=models.CharField(default='Adınızı daxil edin', max_length=255, verbose_name='Ad üçün qeyd'),
        ),
        migrations.AlterField(
            model_name='contactcompanyform',
            name='content_placeholder',
            field=models.CharField(default='Məktubun mətnini daxil edin', max_length=1000, verbose_name='Mətn üçün qeyd'),
        ),
        migrations.AlterField(
            model_name='contactcompanyform',
            name='subject_placeholder',
            field=models.CharField(default='Məktubun mövzusunu daxil edin', max_length=255, verbose_name='Mövzu üçün qeyd'),
        ),
    ]
