# Generated by Django 2.1.5 on 2019-02-10 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0012_auto_20190207_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactcompany',
            options={'verbose_name': 'Müəssisənin əlaqə məlumatı', 'verbose_name_plural': 'Müəssisənin əlaqə məlumatları'},
        ),
        migrations.AlterModelOptions(
            name='contactcompanyform',
            options={'verbose_name': 'Müəssisəyə əlaqə formasının ayarları', 'verbose_name_plural': 'Müəssisəyə əlaqə formasının ayarları'},
        ),
        migrations.AlterModelOptions(
            name='contactcompanyreceivedemails',
            options={'verbose_name': 'Müəssisəyə gələn məktub', 'verbose_name_plural': 'Müəssisəyə gələn məktublar'},
        ),
    ]
