# Generated by Django 2.1.5 on 2019-02-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0013_auto_20190210_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactcompanyform',
            options={'verbose_name': 'Müəssisənin əlaqə formasının ayarları', 'verbose_name_plural': 'Müəssisənin əlaqə formasının ayarları'},
        ),
    ]
