# Generated by Django 2.1.5 on 2019-02-10 07:41

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_name', models.CharField(max_length=255, verbose_name='Müəssisənin adı')),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Haqqımızda')),
                ('main_duties', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Əsas vəzifələr')),
                ('administration', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Rəhbərlik')),
                ('achievements', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Nailiyyətlərimiz')),
                ('admission_requirements', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Qəbul qaydaları')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adres')),
                ('phone_number', models.CharField(blank=True, max_length=25, verbose_name='Telefon')),
                ('about_images', models.ImageField(blank=True, upload_to='media', verbose_name='Şəkil')),
                ('main_activity', models.CharField(blank=True, max_length=255, verbose_name='Fəaliyyət')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Müəssisə',
                'verbose_name_plural': 'Müəssisələr',
            },
        ),
        migrations.CreateModel(
            name='CompanyActivityAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255, verbose_name='Fəaliyyət sahəsi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies')),
            ],
            options={
                'verbose_name': 'Fəaliyyət sahəsi',
                'verbose_name_plural': 'Fəaliyyət sahələri',
            },
        ),
        migrations.CreateModel(
            name='CompanyActivityLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_location', models.CharField(max_length=255, verbose_name='Yerləşdiyi məkan')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies')),
            ],
            options={
                'verbose_name': 'Təşkil olunduğu yer',
                'verbose_name_plural': 'Təşkil olunduğu yerlər',
            },
        ),
        migrations.CreateModel(
            name='CompanyAdministration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Adı və soyadı')),
                ('occupation', models.CharField(max_length=255, verbose_name='Tutduğu vəzifə')),
                ('administration_type', models.CharField(max_length=255, verbose_name='İdarə növü')),
                ('branch_icon', models.ImageField(upload_to='media', verbose_name='Filialın emblemi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies')),
            ],
            options={
                'verbose_name': 'Rəhbərlik',
                'verbose_name_plural': 'Rəhbərlik',
            },
        ),
        migrations.CreateModel(
            name='CompanyInformativePages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=40)),
                ('short_description', models.CharField(max_length=255)),
                ('full_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies')),
            ],
            options={
                'verbose_name': 'İnformativ səhifə',
                'verbose_name_plural': 'İnformativ səhifələr',
            },
        ),
    ]
