# Generated by Django 2.1.5 on 2019-02-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyadministration',
            name='company',
        ),
        migrations.DeleteModel(
            name='CompanyAdministration',
        ),
    ]
