# Generated by Django 2.1.5 on 2019-01-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_companyinformativepages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administration',
            new_name='CompanyAdministration',
        ),
        migrations.RenameModel(
            old_name='PhotoGallery',
            new_name='CompanyPhotoGallery',
        ),
        migrations.RenameModel(
            old_name='VideoGallery',
            new_name='CompanyVideoGallery',
        ),
    ]
