# Generated by Django 2.1.5 on 2019-01-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0003_auto_20190111_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
