# Generated by Django 2.1.5 on 2019-01-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0004_companies_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
