# Generated by Django 2.1.5 on 2019-01-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0005_companies_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
