# Generated by Django 2.1.5 on 2019-01-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0010_auto_20190115_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyphotogallery',
            name='photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
