# Generated by Django 2.1.5 on 2019-01-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0011_auto_20190116_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='companyphotogallery',
            name='photo_file',
            field=models.FileField(default='', upload_to='media'),
        ),
    ]
