# Generated by Django 2.1.5 on 2019-01-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0012_auto_20190119_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='main_duties',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
