# Generated by Django 2.1.5 on 2019-01-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0013_companies_main_duties'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='about_images',
            field=models.ImageField(default='', upload_to='media'),
            preserve_default=False,
        ),
    ]
