# Generated by Django 2.1.5 on 2019-01-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0015_auto_20190121_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyadministration',
            name='about_images',
        ),
        migrations.AddField(
            model_name='companies',
            name='about_images',
            field=models.ImageField(default='', upload_to='media'),
            preserve_default=False,
        ),
    ]
