# Generated by Django 2.1.5 on 2019-01-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0016_auto_20190121_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='regulation_file',
        ),
        migrations.AddField(
            model_name='companies',
            name='legislation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
