# Generated by Django 2.1.5 on 2019-01-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0017_auto_20190123_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='legislation',
        ),
    ]
