# Generated by Django 2.1.5 on 2019-01-31 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0020_auto_20190131_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='profile_id',
        ),
    ]
