# Generated by Django 2.1.5 on 2019-01-31 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0021_remove_companyprofile_profile_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
    ]
