# Generated by Django 2.1.5 on 2019-01-31 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0022_delete_companyprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name': 'Müəssisə', 'verbose_name_plural': 'Müəssisələr'},
        ),
        migrations.AlterModelOptions(
            name='companyadministration',
            options={'verbose_name': 'Rəhbərlik', 'verbose_name_plural': 'Rəhbərlik'},
        ),
        migrations.RemoveField(
            model_name='companyadministration',
            name='parent_id',
        ),
    ]
