# Generated by Django 2.1.5 on 2019-01-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0023_auto_20190131_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='companyadministration',
            old_name='company_id',
            new_name='company',
        ),
    ]
