# Generated by Django 2.1.5 on 2019-01-31 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0024_auto_20190131_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinformativepages',
            options={'verbose_name': 'İnformativ səhifə', 'verbose_name_plural': 'İnformativ səhifələr'},
        ),
        migrations.RenameField(
            model_name='companyinformativepages',
            old_name='company_id',
            new_name='company',
        ),
    ]
