# Generated by Django 2.1.5 on 2019-01-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0025_auto_20190131_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformativepages',
            name='full_content',
            field=models.TextField(),
        ),
    ]
