# Generated by Django 2.1.5 on 2019-01-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0027_auto_20190131_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGalleryPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ManyToManyField(to='company_app.CompanyPhotoGallery')),
            ],
        ),
    ]
