# Generated by Django 2.1.5 on 2019-01-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0028_companygalleryphotos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companygalleryphotos',
            options={'verbose_name': 'Şəkil qalereyası', 'verbose_name_plural': 'Şəkil qalereyası'},
        ),
        migrations.RemoveField(
            model_name='companygalleryphotos',
            name='photo',
        ),
        migrations.AddField(
            model_name='companygalleryphotos',
            name='photo',
            field=models.ImageField(default='', upload_to='', verbose_name='Şəkil'),
            preserve_default=False,
        ),
    ]
