# Generated by Django 2.1.5 on 2019-01-31 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0029_auto_20190131_1415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyGalleryPhotos',
        ),
        migrations.AlterModelOptions(
            name='companyphotogallery',
            options={'verbose_name': 'Şəkil qalereyası', 'verbose_name_plural': 'Şəkil qalereyası'},
        ),
    ]
