# Generated by Django 2.1.5 on 2019-01-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0030_auto_20190131_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGalleryPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'Şəkil',
                'verbose_name_plural': 'Şəkillər',
            },
        ),
        migrations.AlterModelOptions(
            name='companyphotogallery',
            options={'verbose_name': 'Photo Gallery', 'verbose_name_plural': 'Photo Galleries'},
        ),
        migrations.AddField(
            model_name='companyphotogallery',
            name='photo',
            field=models.ManyToManyField(to='company_app.CompanyGalleryPhotos'),
        ),
    ]
