# Generated by Django 2.1.5 on 2019-02-02 14:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0031_auto_20190131_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyphotogallery',
            options={'verbose_name': 'Şəkil Qalereyası', 'verbose_name_plural': 'Şəkil Qalereyası'},
        ),
        migrations.AlterField(
            model_name='companyphotogallery',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
