# Generated by Django 2.1.5 on 2019-02-02 19:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0032_auto_20190202_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='companies',
            name='admission_requirements',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='companies',
            name='main_duties',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='companyinformativepages',
            name='full_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='companyvideogallery',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
