# Generated by Django 2.1.5 on 2019-02-02 20:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0033_auto_20190202_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
