# Generated by Django 2.1.5 on 2019-02-03 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0036_auto_20190203_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOrgLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Təşkil olunduğu yer')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies')),
            ],
            options={
                'verbose_name': 'Təşkil olunduğu yer',
                'verbose_name_plural': 'Təşkil olunduğu yerlər',
            },
        ),
        migrations.AlterModelOptions(
            name='companyactivityareas',
            options={'verbose_name': 'Fəaliyyət sahəsi', 'verbose_name_plural': 'Fəaliyyət sahələri'},
        ),
    ]
