# Generated by Django 2.1.5 on 2019-02-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0037_auto_20190203_0909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyOrgLocations',
            new_name='CompanyLocations',
        ),
    ]
