# Generated by Django 2.1.5 on 2019-02-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0038_auto_20190203_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companylocations',
            options={'verbose_name': 'Təşkil olunduğu yer', 'verbose_name_plural': 'Təşkil olunduğu yer'},
        ),
        migrations.RenameField(
            model_name='companylocations',
            old_name='location',
            new_name='loc',
        ),
    ]
