# Generated by Django 2.1.5 on 2019-02-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0039_auto_20190203_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companylocations',
            options={'verbose_name': 'Təşkil olunduğu yer', 'verbose_name_plural': 'Təşkil olunduğu yerlər'},
        ),
        migrations.RenameField(
            model_name='companylocations',
            old_name='loc',
            new_name='location',
        ),
    ]
