# Generated by Django 2.1.5 on 2019-02-03 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0040_auto_20190203_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyphotogallery',
            name='photo',
        ),
        migrations.AddField(
            model_name='companygalleryphotos',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company_app.CompanyPhotoGallery'),
            preserve_default=False,
        ),
    ]
