# Generated by Django 2.1.5 on 2019-02-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0041_auto_20190203_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyphotogallery',
            name='photo_file',
            field=models.ImageField(default='', upload_to='media', verbose_name='Əsas şəkil'),
        ),
    ]
