# Generated by Django 2.1.5 on 2019-02-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0043_auto_20190204_0904'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyYerler',
            new_name='CompanyLocations',
        ),
        migrations.RenameField(
            model_name='companylocations',
            old_name='yer',
            new_name='location',
        ),
    ]
