# Generated by Django 2.1.5 on 2019-02-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0044_auto_20190204_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companylocations',
            name='company',
        ),
        migrations.DeleteModel(
            name='CompanyLocations',
        ),
    ]
