# Generated by Django 2.1.5 on 2019-02-04 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0045_auto_20190204_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyActivityLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_location', models.CharField(max_length=255, verbose_name='Yerləşdiyi məkan')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies')),
            ],
            options={
                'verbose_name': 'Təşkil olunduğu yer',
                'verbose_name_plural': 'Təşkil olunduğu yerlər',
            },
        ),
    ]
