# Generated by Django 2.1.5 on 2019-02-04 14:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0046_companyactivitylocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='administration',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Rəhbərlik'),
        ),
    ]
