# Generated by Django 2.1.5 on 2019-02-04 14:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0047_companies_administration'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='achievements',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Nailiyyətlərimiz'),
        ),
    ]
