# Generated by Django 2.1.5 on 2019-02-04 19:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0048_companies_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='achievements',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Nailiyyətlərimiz'),
            preserve_default=False,
        ),
    ]
