# Generated by Django 2.1.5 on 2019-02-05 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0050_auto_20190204_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companygalleryphotos',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyphotogallery',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyvideogallery',
            name='company',
        ),
        migrations.DeleteModel(
            name='CompanyGalleryPhotos',
        ),
        migrations.DeleteModel(
            name='CompanyPhotoGallery',
        ),
        migrations.DeleteModel(
            name='CompanyVideoGallery',
        ),
    ]
