# Generated by Django 2.1.5 on 2019-02-10 11:44

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_app', '0002_auto_20190210_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies')),
            ],
            options={
                'verbose_name': 'Xəbərin Kateqoriyası',
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='CompanyNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('news_picture', models.ImageField(upload_to='media', verbose_name='Xəbərin əsas şəkli')),
                ('short_description', models.TextField(max_length=255, verbose_name='Qısa təsvir')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Xəbərin mətni')),
                ('publish_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies')),
            ],
            options={
                'verbose_name': 'Müəssisənin xəbəri',
                'verbose_name_plural': 'Müəssisənin xəbərləri',
            },
        ),
        migrations.CreateModel(
            name='CompanyNewsSlideImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company_news_slides', verbose_name='Xəbər üçün slayd şəkli')),
                ('weight', models.IntegerField(default=1, verbose_name='Şəklin sırası')),
                ('company_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.CompanyNews', verbose_name='Xəbər')),
            ],
            options={
                'verbose_name': 'Müəssisənin xəbəri üçün slayd şəkil',
                'verbose_name_plural': 'Müəssisənin xəbəri üçün slayd şəkillər',
            },
        ),
        migrations.CreateModel(
            name='MainNewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Əsas xəbərin kateqoriyası',
                'verbose_name_plural': 'Əsas xəbərin kateqoriyaları',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('news_picture', models.ImageField(upload_to='media', verbose_name='Xəbərin əsas şəkli')),
                ('short_description', models.TextField(max_length=255, verbose_name='Qısa təsvir')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Xəbərin mətni')),
                ('type', models.IntegerField(choices=[(1, 'Xəbər'), (2, 'Tədbir')])),
                ('publish_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.MainNewsCategory')),
            ],
            options={
                'verbose_name': 'Xəbər',
                'verbose_name_plural': 'Xəbərlər',
            },
        ),
        migrations.CreateModel(
            name='NewsSlideImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company_news_slides', verbose_name='Xəbər üçün slayd şəkli')),
                ('weight', models.IntegerField(default=1, verbose_name='Şəklin sırası')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.News', verbose_name='Xəbər')),
            ],
            options={
                'verbose_name': 'Slayd üçün şəkil',
                'verbose_name_plural': 'Slayd üçün şəkillər',
            },
        ),
    ]
