# Generated by Django 2.1.5 on 2019-02-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companynews',
            options={'verbose_name': 'Müəssisənin xəbəri', 'verbose_name_plural': 'Müəssisənin xəbərləri'},
        ),
        migrations.AlterModelOptions(
            name='companynewsslideimages',
            options={'verbose_name': 'Müəssisənin xəbəri üçün slayd şəkil', 'verbose_name_plural': 'Müəssisənin xəbəri üçün slayd şəkillər'},
        ),
    ]
