# Generated by Django 2.1.5 on 2019-01-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='news_picture',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_picture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
