# Generated by Django 2.1.5 on 2019-01-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_auto_20190111_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='full_content',
            new_name='full_description',
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companynews',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
