# Generated by Django 2.1.5 on 2019-02-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_remove_news_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.IntegerField(choices=[(1, 'Xəbər'), (2, 'Tədbir')], default=1),
        ),
    ]
