# Generated by Django 2.1.5 on 2019-01-30 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0019_auto_20190124_0746'),
        ('news_app', '0004_auto_20190124_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='full_content',
            new_name='long_description',
        ),
        migrations.AddField(
            model_name='news',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
