# Generated by Django 2.1.5 on 2019-01-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_auto_20190130_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='company_id',
        ),
    ]
