# Generated by Django 2.1.5 on 2019-02-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_auto_20190210_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Xəbər və Tədbir', 'verbose_name_plural': 'Xəbərlər və Tədbirlər'},
        ),
    ]
