# Generated by Django 2.1.5 on 2019-02-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_auto_20190210_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['type', 'title'], 'verbose_name': 'Xəbər və Tədbir', 'verbose_name_plural': 'Xəbərlər və Tədbirlər'},
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.IntegerField(choices=[(1, 'Xəbər'), (2, 'Tədbir'), (3, 'Çıxış')], db_index=True, default=1),
        ),
    ]
