# Generated by Django 2.1.5 on 2019-02-07 13:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_auto_20190131_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companynews',
            options={'verbose_name': 'MÜəssisənin xəbəri', 'verbose_name_plural': 'Müəssisənin xəbərləri'},
        ),
        migrations.RemoveField(
            model_name='companynews',
            name='long_description',
        ),
        migrations.AlterField(
            model_name='companynews',
            name='news_picture',
            field=models.ImageField(upload_to='media', verbose_name='Xəbərin əsas şəkli'),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Qısa təsvir'),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Xəbərin mətni'),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Başlıq'),
        ),
    ]
