# Generated by Django 2.1.5 on 2019-02-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0009_auto_20190207_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.TextField(max_length=255),
        ),
    ]
