# Generated by Django 2.1.5 on 2019-02-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0011_auto_20190207_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscategories',
            name='category_id',
        ),
        migrations.RenameField(
            model_name='companynews',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='companynews',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='category_id',
            new_name='category',
        ),
        migrations.DeleteModel(
            name='NewsCategories',
        ),
    ]
