# Generated by Django 2.1.5 on 2019-02-09 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0012_auto_20190209_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNewsSlideImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field=315, upload_to='company_news_slides', verbose_name='Xəbər üçün slayd şəkli')),
                ('weight', models.IntegerField(verbose_name='Şəklin sırası')),
                ('company_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.CompanyNews', verbose_name='Xəbər')),
            ],
        ),
    ]
