# Generated by Django 2.1.5 on 2019-02-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0013_companynewsslideimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companynewsslideimages',
            options={'verbose_name': 'Slayd üçün şəkil', 'verbose_name_plural': 'Slayd üçün şəkillər'},
        ),
        migrations.AlterField(
            model_name='companynewsslideimages',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='Şəklin sırası'),
        ),
    ]
