# Generated by Django 2.1.5 on 2019-02-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0014_auto_20190209_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynewsslideimages',
            name='image',
            field=models.ImageField(upload_to='company_news_slides', verbose_name='Xəbər üçün slayd şəkli'),
        ),
    ]
