# Generated by Django 2.1.5 on 2019-02-10 05:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0015_auto_20190209_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Xəbər', 'verbose_name_plural': 'Xəbərlər'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='long_description',
        ),
        migrations.AlterField(
            model_name='news',
            name='news_picture',
            field=models.ImageField(upload_to='media', verbose_name='Xəbərin əsas şəkli'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.TextField(max_length=255, verbose_name='Qısa təsvir'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Xəbərin mətni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Başlıq'),
        ),
    ]
