# Generated by Django 2.1.5 on 2019-02-10 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0051_auto_20190205_0430'),
        ('news_app', '0016_auto_20190210_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSlideImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company_news_slides', verbose_name='Xəbər üçün slayd şəkli')),
                ('weight', models.IntegerField(default=1, verbose_name='Şəklin sırası')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.News', verbose_name='Xəbər')),
            ],
            options={
                'verbose_name': 'Slayd üçün şəkil',
                'verbose_name_plural': 'Slayd üçün şəkillər',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='profile',
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies'),
            preserve_default=False,
        ),
    ]
