# Generated by Django 2.1.5 on 2019-02-10 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0017_auto_20190210_0537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companynewsslideimages',
            options={'verbose_name': 'Şirkətin xəbəri üçün slayd şəkil', 'verbose_name_plural': 'Şirkətin xəbəri üçün slayd şəkillər'},
        ),
    ]
