# Generated by Django 2.1.5 on 2019-01-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformativPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=40)),
                ('short_description', models.CharField(max_length=255)),
                ('full_content', models.CharField(max_length=255)),
            ],
        ),
    ]
