# Generated by Django 2.1.5 on 2019-01-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InformativPages',
            new_name='MainInformativePages',
        ),
    ]
