# Generated by Django 2.1.5 on 2019-01-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_generalinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinformation',
            name='title',
        ),
    ]
