# Generated by Django 2.1.5 on 2019-02-02 19:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_exits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maininformativepages',
            options={'verbose_name': 'İnformativ səhifə', 'verbose_name_plural': 'İnformativ səhifələr'},
        ),
        migrations.AlterField(
            model_name='maininformativepages',
            name='full_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=255),
        ),
        migrations.AlterField(
            model_name='maininformativepages',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Başlıq'),
        ),
    ]
