# Generated by Django 2.1.5 on 2019-02-02 19:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20190202_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininformativepages',
            name='full_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Kontent'),
        ),
        migrations.AlterField(
            model_name='maininformativepages',
            name='short_description',
            field=models.TextField(max_length=255, verbose_name='Qısa təsvir'),
        ),
        migrations.AlterField(
            model_name='maininformativepages',
            name='slug',
            field=models.SlugField(max_length=40, verbose_name='Slug'),
        ),
    ]
