# Generated by Django 2.1.5 on 2019-02-02 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20190202_1952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralInformation',
        ),
        migrations.AlterModelOptions(
            name='attributes',
            options={'verbose_name': 'Atribut', 'verbose_name_plural': 'Atributlar'},
        ),
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'Sənəd', 'verbose_name_plural': 'Sənədlər'},
        ),
    ]
