# Generated by Django 2.1.5 on 2019-02-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20190202_2037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exits',
            new_name='Speeches',
        ),
        migrations.AlterModelOptions(
            name='speeches',
            options={'verbose_name': 'Çıxış', 'verbose_name_plural': 'Çıxışlar'},
        ),
    ]
