# Generated by Django 2.1.5 on 2019-02-10 07:41

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGalleryPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='company_gallery_photos', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'Müəssisənin qalereyası üçün şəkil',
                'verbose_name_plural': 'Müəssisənin qalereyası üçün şəkillər',
            },
        ),
        migrations.CreateModel(
            name='CompanyGalleryVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='company_gallery_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'mpeg'])], verbose_name='Video fayl')),
            ],
            options={
                'verbose_name': 'Müəssisənin qalereyası üçün video',
                'verbose_name_plural': 'Müəssisənin qalereyası üçün videolar',
            },
        ),
        migrations.CreateModel(
            name='CompanyPhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file', models.ImageField(default='', upload_to='company_gallery_photo', verbose_name='Əsas şəkil')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Qalereyanın mətni')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies', verbose_name='Müəssisə')),
            ],
            options={
                'verbose_name': 'Müəssisənin Şəkil Qalereyası',
                'verbose_name_plural': 'Müəssisənin Şəkil Qalereyaları',
            },
        ),
        migrations.CreateModel(
            name='CompanyVideoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file', models.ImageField(default='', upload_to='company_video_gallery_photo', verbose_name='Əsas şəkil')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Qalereyanın mətni')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies', verbose_name='Müəssisə')),
            ],
            options={
                'verbose_name': 'Müəssisənin Video Qalereyası',
                'verbose_name_plural': 'Müəssisənin Video Qalereyaları',
            },
        ),
        migrations.AddField(
            model_name='companygalleryvideos',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_app.CompanyVideoGallery'),
        ),
        migrations.AddField(
            model_name='companygalleryphotos',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_app.CompanyPhotoGallery'),
        ),
    ]
