# Generated by Django 2.1.5 on 2019-02-05 04:30

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_app', '0051_auto_20190205_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGalleryPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'Şəkil',
                'verbose_name_plural': 'Şəkillər',
            },
        ),
        migrations.CreateModel(
            name='CompanyPhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file', models.ImageField(default='', upload_to='media', verbose_name='Əsas şəkil')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Kontent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies', verbose_name='Müəssisə')),
            ],
            options={
                'verbose_name': 'Şəkil Qalereyası',
                'verbose_name_plural': 'Şəkil Qalereyası',
            },
        ),
        migrations.CreateModel(
            name='CompanyVideoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='media')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies')),
            ],
            options={
                'verbose_name': 'Video Gallery',
                'verbose_name_plural': 'Video Galleries',
            },
        ),
        migrations.AddField(
            model_name='companygalleryphotos',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_app.CompanyPhotoGallery'),
        ),
    ]
