# Generated by Django 2.1.5 on 2019-02-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companygalleryphotos',
            old_name='company',
            new_name='gallery',
        ),
    ]
