# Generated by Django 2.1.5 on 2019-02-09 21:28

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_auto_20190205_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyvideogallery',
            options={'verbose_name': 'Video Qalereya', 'verbose_name_plural': 'Video Qalereyalar'},
        ),
        migrations.RemoveField(
            model_name='companyvideogallery',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='companyphotogallery',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Qalereyanın mətni'),
        ),
        migrations.AlterField(
            model_name='companyvideogallery',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies', verbose_name='Müəssisə'),
        ),
        migrations.AlterField(
            model_name='companyvideogallery',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Qalereyanın mətni'),
        ),
    ]
