# Generated by Django 2.1.5 on 2019-02-09 21:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0003_auto_20190209_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGalleryVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'mpeg'])], verbose_name='Video fayl')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_app.CompanyVideoGallery')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
            },
        ),
    ]
