# Generated by Django 2.1.5 on 2019-02-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0004_companygalleryvideos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companygalleryvideos',
            old_name='file',
            new_name='video_file',
        ),
    ]
