# Generated by Django 2.1.5 on 2019-02-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0005_auto_20190209_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvideogallery',
            name='photo_file',
            field=models.ImageField(default='', upload_to='media', verbose_name='Əsas şəkil'),
        ),
    ]
