# Generated by Django 2.1.5 on 2019-02-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0006_companyvideogallery_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyphotogallery',
            name='photo_file',
            field=models.ImageField(default='', upload_to='company_photo_gallery_photo', verbose_name='Əsas şəkil'),
        ),
        migrations.AlterField(
            model_name='companyvideogallery',
            name='photo_file',
            field=models.ImageField(default='', upload_to='company_video_gallery_photo', verbose_name='Əsas şəkil'),
        ),
    ]
