# Generated by Django 2.1.5 on 2019-02-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0007_auto_20190209_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companygalleryvideos',
            old_name='video_file',
            new_name='file',
        ),
    ]
