# Generated by Django 2.1.5 on 2019-02-10 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0009_auto_20190209_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companygalleryphotos',
            options={'verbose_name': 'Müəssisənin qalereyası üçün şəkil', 'verbose_name_plural': 'Müəssisənin qalereyası üçün şəkillər'},
        ),
        migrations.AlterModelOptions(
            name='companygalleryvideos',
            options={'verbose_name': 'Müəssisənin qalereyası üçün video', 'verbose_name_plural': 'Müəssisənin qalereyası üçün videolar'},
        ),
        migrations.AlterModelOptions(
            name='companyphotogallery',
            options={'verbose_name': 'Müəssisənin Şəkil Qalereyası', 'verbose_name_plural': 'Müəssisənin Şəkil Qalereyaları'},
        ),
        migrations.AlterModelOptions(
            name='companyvideogallery',
            options={'verbose_name': 'Müəssisənin Video Qalereyası', 'verbose_name_plural': 'Müəssisənin Video Qalereyaları'},
        ),
    ]
