# Generated by Django 2.1.5 on 2019-02-10 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('building_name', models.CharField(blank=True, max_length=25, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies')),
            ],
        ),
    ]
