# Generated by Django 2.1.5 on 2019-01-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maplocations',
            old_name='langitude',
            new_name='longitude',
        ),
    ]
