# Generated by Django 2.1.5 on 2019-02-10 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_type', models.IntegerField(choices=[(1, 'Medal alanlar'), (2, 'Fərqlənənlər')], verbose_name='Kateqoriya')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ad və Soyad')),
                ('short_description', models.TextField(max_length=255, verbose_name='Qısa təsvir')),
                ('image', models.ImageField(upload_to='media', verbose_name='Şəkil')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies')),
            ],
            options={
                'verbose_name': 'Fərqlənənlər və Medal alanlar',
                'verbose_name_plural': 'Fərqlənənlər və Medal alanlar',
            },
        ),
    ]
