# Generated by Django 2.1.5 on 2019-01-11 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_app', '0002_companyinformativepages'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('vip_type', models.CharField(choices=[('MEDAL_ALANLAR', 'medal_alanlar'), ('FERQLENENLER', 'ferqlenenler')], max_length=255)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_app.Companies')),
            ],
        ),
    ]
