# Generated by Django 2.1.5 on 2019-01-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='vip_type',
            field=models.CharField(choices=[('MA', 'medal_alanlar'), ('FQ', 'ferqlenenler')], max_length=255),
        ),
    ]
