# Generated by Django 2.1.5 on 2019-01-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_app', '0002_auto_20190111_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='image',
            field=models.ImageField(default='', upload_to='media'),
            preserve_default=False,
        ),
    ]
