# Generated by Django 2.1.5 on 2019-01-22 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vip_app', '0003_vip_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('vip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='vip_app.VIP')),
            ],
        ),
    ]
