# Generated by Django 2.1.5 on 2019-01-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_app', '0004_vipdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipdescription',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
