# Generated by Django 2.1.5 on 2019-01-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_app', '0005_auto_20190122_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipdescription',
            name='short_description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vipdescription',
            name='text',
            field=models.TextField(),
        ),
    ]
