# Generated by Django 2.1.5 on 2019-02-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_app', '0007_auto_20190123_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='vip_type',
            field=models.CharField(choices=[(1, 'medal_alanlar'), (2, 'ferqlenenler')], max_length=255),
        ),
    ]
