# Generated by Django 2.1.5 on 2019-02-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vip_app', '0008_auto_20190204_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vip',
            old_name='company_id',
            new_name='company',
        ),
    ]
