# Generated by Django 2.1.5 on 2019-02-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_app', '0009_auto_20190204_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vip',
            name='text',
        ),
        migrations.AlterField(
            model_name='vip',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Ad və Soyad'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Qısa təsvir'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='vip_type',
            field=models.CharField(choices=[(1, 'medal_alanlar'), (2, 'ferqlenenler')], max_length=255, verbose_name='Kateqoriya'),
        ),
    ]
