# Generated by Django 2.1.5 on 2019-02-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_app', '0010_auto_20190204_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='vip_type',
            field=models.CharField(choices=[(1, 'Medal alanlar'), (2, 'Fərqlənənlər')], max_length=255, verbose_name='Kateqoriya'),
        ),
    ]
