# Generated by Django 2.1.5 on 2019-02-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_app', '0012_auto_20190204_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='short_description',
            field=models.TextField(max_length=255, verbose_name='Qısa təsvir'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='vip_type',
            field=models.IntegerField(choices=[(1, 'Medal alanlar'), (2, 'Fərqlənənlər')], verbose_name='Kateqoriya'),
        ),
    ]
