# Generated by Django 2.1.5 on 2019-02-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vip_app', '0013_auto_20190204_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vip',
            options={'verbose_name': 'Fərqlənənlər və Medal alanlar', 'verbose_name_plural': 'Fərqlənənlər və Medal alanlar'},
        ),
    ]
