# Generated by Django 2.1.5 on 2019-02-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Müəssisəyə tez-tez verilən sual',
                'verbose_name_plural': 'Müəssisəyə tez-tez verilən suallar',
            },
        ),
        migrations.CreateModel(
            name='MainFaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
    ]
