# Generated by Django 2.1.5 on 2019-02-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ_app', '0002_faq_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainfaq',
            options={'verbose_name': 'Tez-tez verilən sual', 'verbose_name_plural': 'Tez-tez verilən suallar'},
        ),
        migrations.AlterField(
            model_name='mainfaq',
            name='answer',
            field=models.TextField(max_length=255),
        ),
    ]
