# Generated by Django 2.1.5 on 2019-02-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ_app', '0004_auto_20190204_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Müəssisəyə tez-tez verilən sual', 'verbose_name_plural': 'Müəssisəyə tez-tez verilən suallar'},
        ),
    ]
